version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Europe/Amsterdam
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - hrapp

  frontend:
    build:
      context: ./app
    ports:
      - "3000:3000"
    networks:
      - hrapp

  api:
    build:
      context: ./api
    ports:
      - "3002:3002"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_HOST: db
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    volumes:
      - /mnt/powershell:/mnt/powershell  # Voeg dit volume toe
    networks:
      - hrapp

networks:
  hrapp:
    driver: bridge
